### ISSUE TITLE
Instructions do not work with CRNA

### ISSUE THREAD

**Issue by hassankhan** [viewstools/yarn-workspaces-cra-crna#1]
```bash
yarn start
yarn run v1.3.2
$ node link-workspaces.js
$ react-native-scripts start
20:00:09: Starting packager...
***ERROR STARTING PACKAGER***
Starting React Native packager...

ENOENT: no such file or directory, stat '/Users/hassankhan/Projects/workspace-project/packages/node_modules'
```

**Comment by dariocravero** [comment]
Can you share the failing repo? Thanks!

**Comment by jpgarcia** [comment]
Facing the same issue here. I found what is causing it and a workaround that do the trick: 

Just replace a line in the `metro-bundler-config-yarn-workspaces` lib with the following:

```js
// path.resolve(from, '..', 'node_modules'),
path.resolve(from, '..', '..', 'node_modules'),
```
I think this is because my workspaces are located inside a `packages` folder

Can we add a new parameter (maybe optional to keep it backward compatible) to the `getConfig` function in order to provide the `node_modules` root folder?

```js
const app = path.resolve(__dirname)
const root = path.resolve(__dirname, '..', '..')

getConfig(app, root)
```

If you agree I can create a PR.

Thanks!

**Comment by hassankhan** [comment]
Apologies @dariocravero, haven't had time time to share a repo, but congatulations @jpgarcia for finding the issue!

**Comment by dariocravero** [comment]
Hey @jpgarcia, yeah, if that sorts it for you guys, happy to take a PR in for it! I guess the idea would be that `path.resolve(from, '..', 'node_modules')` is a default for a nodeModules param, right? Maybe that can be an object as the second argument `getConfig`? Thanks!

**Comment by Connorelsea** [comment]
I tried making these changes in my project, following @jpgarcia's advice but still end up with this. Any idea what it could be?

Putting debug comments in rn-cli.config.js seems to generate the correct paths, so why still failing with seemingly no error?

![image](https://user-images.githubusercontent.com/1844458/34701115-0513b3f4-f4ac-11e7-90cd-f05bb26363a0.png)

![image](https://user-images.githubusercontent.com/1844458/34701091-e51a774a-f4ab-11e7-9eb0-60b2d6858d3c.png)

**Comment by Connorelsea** [comment]
Eventually got this working using @jpgarcia's instructions. Nice work, would love a PR

**Comment by jpgarcia** [comment]
Hey @dariocravero did you have time to look the PR I sent? any chances to get this merged? 

Let me know if you have any feedback,
thanks!

**Comment by dariocravero** [comment]
Amazing! Thanks @jpgarcia, merged!
